-- Streaming Media Database

CREATE DATABASE streamingMedia;

USE streamingMedia;

CREATE TABLE Countries (ID INT NOT NULL AUTO_INCREMENT, Name VARCHAR(50) NOT NULL UNIQUE, PRIMARY KEY(ID));

CREATE TABLE Categories(ID INT NOT NULL AUTO_INCREMENT, Name VARCHAR(50), PRIMARY KEY(ID));

CREATE TABLE Movie(ID INT NOT NULL AUTO_INCREMENT, Title VARCHAR(100) NOT NULL UNIQUE, Years YEAR(4), Duration TIME(30000), Category_id INT, Country_id INT,
PRIMARY KEY(ID), FOREIGN KEY(Category_id) REFERENCES Categories(ID), FOREIGN KEY(Country_id) REFERENCES Countries(ID) );


